### ISSUE TITLE
Not working very well for archived chats

### ISSUE THREAD

**Issue by ranolfi** [tomer8007/whatsapp-web-incognito#81]
As in title. More specifically:

1. Sometimes it blocks the read receipts but doesn't give the option to send them
2. Other times it'll fail, by sending read receipts when I don't want it to
3. These issues appear to persist after I "unarchive" a chat through the browser.

This is with `Chromium Version 99.0.4844.84 (Official Build) Arch Linux (64-bit)` and `WAIncognito 1.8.5`.

P.s. Thank you for developing this tool and making it open source.

**Comment by ranolfi** [comment]
Oh, should've mentioned this is with the new "multi-device mode" which btw I would love to be able to turn off but apparently it's official now.

**Comment by tomer8007** [comment]
This should now be fixed in 1.8.6 (6eb8d985f2440d0eba2f90c9e3be8e47d89cb61a).

**Comment by ranolfi** [comment]
I tested by loading it manually. Appears to have fixed the reported issue indeed. For some reason, though, for archived chats the 'mark as read' option does clear up the unread message count (i.e. it works), but not on the browser... if I open WhatsApp on my phone, the unread messages are cleared up, but they still appear as unread in the browser, even after reloading the page.

This is observed only for archived chats.

Additionally, an error is reported:

![image](https://user-images.githubusercontent.com/8507649/162596328-1fba43de-d604-49f6-b57c-d9db3a32b569.png)

Disabling and re-enabling the extension does not fix it, a reloading does.

**Comment by tomer8007** [comment]
I just tested this by clicking on an archived chat with pending messages. When I marked the chat as read, the unread counter cleared up in both the browser and the phone. Do you have other instructions to reproduce this?
(The error you have is actually quite normal, it happens when the WebSocket connection is rest. I'll get rid of it in the future).
